name: Deploy Next.js site to anshumemorial.in

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    #    steps:
    #      - name: executing remote ssh commands using ssh key
    #        uses: appleboy/ssh-action@master
    #        with:
    #          host: ${{ secrets.HOST }}
    #          username: ${{ secrets.USERNAME }}
    #          key: ${{ secrets.SSHKEY }}
    #          port: ${{ secrets.PORT }}
    #          script: "cd ~/public_html/next-cicd-ama/ && ./.scripts/deploy.sh"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      # from here -- setup github page
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
      # end here -- setup github page
      - name: Install NPM Dependencies
        run: npm i
      - name: Build and Export Static Project
        run: npm run export
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # name: next-static-export
          path: ./out
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v3
        with:
          name: next-static-export
          path: ./out
  # Deployment job
  deploy_gh:
    name: Deploy to gh-page
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  # Deploy Job
  deploy_web:
    name: Deploy to website
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: actions/checkout@v3
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: next-static-export
          path: ./out
      - name: file location
        run: pwd
        working-directory: ./out
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --progress
          path: ./out
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSHKEY }}
